offers-datasource:
    protocol: "postgresql"
    host: "locahost"
    port: "5432"
    database: "offers"
    credentials:
        user: "sa"
        password: ""
    read-only: true
    pool:
        connections:
            min: 1
            max: 3
    ssl:
        enabled: true
        mode: "allow"
logging:
    level:
        ROOT: ERROR
spring:
    main:
        banner-mode: off
    jmx:
        enabled: false
management:
    health:
        r2dbc:
            enabled: false
